### ISSUE TITLE
5.1测试不通过

### ISSUE THREAD

**Issue by ecol0408** [aJIEw/PhoneCallApp#1]
在Nexus5手机5.1版本的系统没任何反应，看别人的做法是拦截通知，然后弹出层。

**Comment by aJIEw** [comment]
6.0 以上才可以替代默认应用，6.0 以下只能监听来电，Demo 现在是拨打或接听电话时才显示顶级弹框，具体代码见：[CallListenerService.java#L87](https://github.com/aJIEw/PhoneCallApp/blob/f02901f4e781a3658b0e683d8054795b10f8dd4f/app/src/main/java/com/ajiew/phonecallapp/listenphonecall/CallListenerService.java#L87)

**Comment by ecol0408** [comment]
好的，感谢。
