### ISSUE TITLE
请教两个问题

### ISSUE THREAD

**Issue by ling9400** [aJIEw/PhoneCallApp#3]
1、鉴于国内的ROM不同，目前开机广播都是监听不到了的，并且应用很容易被杀掉，所以自启是个问题。
2、你推荐的博客里面也说了，到5.0之后接听实现不了，而且目前9.0的话挂断也不行了。

**Comment by aJIEw** [comment]
1、国内 rom 可以监听开机广播的吧，只不过需要用户授权，你可以在手机上找下自启动管理。
2、保活和自启动是两个话题，只有使用第二种方式监听来电才需要保活，而且保活是一个古老的话题，目前也没有完美的方案。
3、博客里什么时候说 5.0 之后接听不了？另外，我尝试了下，9.0 下工作正常。

最后，如果发现 bug，麻烦写明重现步骤。
