### ISSUE TITLE
顶部弹的拒接和接听的框是系统的吗，我这边装怎么没弹，同一个手机看到其他应用有弹，这个是在什么情况下弹的

### ISSUE THREAD

**Issue by hukejia** [aJIEw/PhoneCallApp#4]

**Comment by aJIEw** [comment]
那个是原生系统默认电话应用的来电弹框，应该不会出现你说的时而有时而无弹框的情况，你再试试，先不要修改默认电话应用

**Comment by hukejia** [comment]
> 那个是原生系统默认电话应用的来电弹框，应该不会出现你说的时而有时而无弹框的情况，你再试试，先不要修改默认电话应用

像腾讯手机管家，已经设置成默认拨号应用，但是界面还是系统的是怎么做的

**Comment by aJIEw** [comment]
> > 那个是原生系统默认电话应用的来电弹框，应该不会出现你说的时而有时而无弹框的情况，你再试试，先不要修改默认电话应用
> 
> 像腾讯手机管家，已经设置成默认拨号应用，但是界面还是系统的是怎么做的

你说的是来电秀吧，那个只是监听电话，并没有设置成默认电话应用。

**Comment by hukejia** [comment]
> > > 那个是原生系统默认电话应用的来电弹框，应该不会出现你说的时而有时而无弹框的情况，你再试试，先不要修改默认电话应用
> > 
> > 
> > 像腾讯手机管家，已经设置成默认拨号应用，但是界面还是系统的是怎么做的
> 
> 你说的是来电秀吧，那个只是监听电话，并没有设置成默认电话应用。

几乎所有的来电应用都会引导设置默认拨号应用，但是设置了之后拨号和接听界面还是系统的，目的是啥呢

**Comment by aJIEw** [comment]
不清楚，可能为了应用保活？

**Comment by hukejia** [comment]
> 不清楚，可能为了应用保活？

还有设置了默认拨号后，很多电话相关的权限不需要动态申请了，但是我还是没搞明白设置默认后怎么让界面依旧是系统的
